name: prathivexample
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

#  `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  shared_preferences: ^2.0.15
  flutter_platform_widgets: ^2.0.0
  fluttertoast: ^8.0.8
  geolocator: ^8.2.1
  location: ^4.4.0
  http: ^0.13.4
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  screenshot: ^1.2.3
  firebase_storage: ^10.2.17
  uuid: ^3.0.6

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true